### PR TITLE
Fix root.log trigger line

### PR DESCRIPTION
**Pull request by tdawson**
Mock in Koji changed a few months ago.  As a result, key parts of the root.log changed.
This fixes the parser so that it can determine when the next section has started.

Signed-off-by: Troy Dawson <tdawson@redhat.com>

### CODE REVIEW

**Comment by sgallagher** [comment]
Wouldn't it be better to go with `'/usr/bin/dnf', 'builddep'` as the key phrase, since that's unlikely to change regardless of what wraps it?

**Comment by hroncok** [comment]
`Executing command: ['/usr/bin/systemd-nspawn'` appears to exist many times in the log, even for other things.

**Comment by tdawson** [comment]
Tested and ```'/usr/bin/dnf', 'builddep'``` does indeed work on both the old logs and the new logs.

**Review by sgallagher — APPROVED** [review]
LGTM

**Pull request merged**
